name: deploy-blog

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: print
        run: |
          echo Hello world!