name: deploy-blog

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      
      - name: npm install
        run: npm install
      
      - name: npm run build
        run: npm run build

      - name : push to repo
        run: |
          git add -f -- _site/
          git config --global user.name "Darren Li"
          git config --global user.email "darren@easychat.co"
          git commit -m "github actions test push"
          git push